### ISSUE TITLE
Initial attempt at building/testing odc for JEDI

### ISSUE THREAD

**Issue by srherbener** [ecmwf/odc#1]
Thank you for the release! I've attempted to build and test odc and I ran into a couple things:

I cloned this repo on my iMac, and checked out tag '1.0.2'. I tried build and test both inside a Singularity container (GNU compilers, OpenMPI) and outside the container (Clang for C, C++ and gfortran for Fortran, MPICH).

I needed to make the following changes to get the build to complete. 
```
sysadmins-iMac:build stephenh$ git diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 6a249d22..80258de2 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -16,7 +16,7 @@ set(CMAKE_CXX_STANDARD_REQUIRED ON)
 ########################################################################################################################
 ### dependencies and options

-ecbuild_use_package( PROJECT eckit  VERSION 1.9 REQUIRED )
+ecbuild_use_package( PROJECT eckit  VERSION 1.4 REQUIRED )

 ecbuild_add_option( FEATURE FORTRAN
                     DESCRIPTION "whether or not to build the Fortran interface"
diff --git a/tests/c_api/encode.cc b/tests/c_api/encode.cc
index f27d6bd1..00e66f6a 100644
--- a/tests/c_api/encode.cc
+++ b/tests/c_api/encode.cc
@@ -541,7 +541,7 @@ CASE("Encode to a file descriptor") {
     // Do the encoding

     eckit::TmpFile tf;
-    int fd = ::open(tf.asString().c_str(), O_CREAT|O_WRONLY);
+    int fd = ::open(tf.asString().c_str(), O_CREAT|O_WRONLY, S_IRUSR|S_IWUSR|S_IRGRP|S_IROTH);
     ASSERT(fd != -1);
     long sz;
     try {
```

The first change (CMakeLists.txt) was necessary for both Clang and GNU compilers (we are on eckit version 1.4.0), the second change (encode.cc) was only necessary for GNU compilers.

I get the following errors, both outside the container (Clang) and inside Singularity (GNU):
```
The following tests FAILED:
	  4 - /Users/stephenh/projects/odc/regressions/ODB-463.sh (Failed)
	199 - odc_test_text_reader_select (Failed)
Errors while running CTest
```

Perhaps these test failures are due to my using a version of eckit older than 1.9?

I tried linking our application with the libraries from this build, and all the tests I have passed. So, it looks like the release code is in good shape in that respect.

**Comment by tlmquintino** [comment]
We have release new versions of eckit and odc. Could you please try those?

Indeed the dependency on eckit 1.9 is correct and is likely the reason for the failed tests.
Note that eckit holds the SQL engine that odc uses, so the dependencies need to be strictly tracked.

Regarding your change in the open() statement, we do not see the addition of these flags as necessary. 
We are able to run the tests in multiple platforms including Mac and Linux environments.
You may need to control the umask of your testing environment to get those tests to succeed.

**Comment by srherbener** [comment]
My apologies - I had forgotten about this issue. Thank you for your diligence in following up with this issue.

Since last year we have upgraded to ecmwf eckit 1.16.0. I just tried the master branch on my iMac (Big Sur, Apple Clang 12.0.0, GNU Fortran 10.2.0). The build succeeded and all the tests pass so all looks good.

I'll go ahead and close this issue.

Thanks!
