### ISSUE TITLE
ODC tests fail when there is no internet connection

### ISSUE THREAD

**Issue by DJDavies2** [ecmwf/odc#4]
Start  9: odc_get_test_data
 1/91 Test  #9: odc_get_test_data ..........................................................................***Failed   31.95 sec
(curl) downloading http://download.ecmwf.org/test-data/odc/tests/2000010106.odb.gz
curl: (28) Connection timed out after 30000 milliseconds
gmake[1]: *** [odc/tests/2000010106.odb.gz] Error 28
gmake: *** [__get_data_odc_get_test_data_2000010106_odb_gz/fast] Error 2
CMake Error at /home/d03/frwd/cylc-run/OdcFailure/share/build-lfric_cray/odc/tests/get_data_odc_get_test_data.cmake:5 (message):
  Error running
Call Stack (most recent call first):
  /home/d03/frwd/cylc-run/OdcFailure/share/build-lfric_cray/odc/tests/get_data_odc_get_test_data.cmake:9 (exec_check)

Looking at the code it seems there is no way this test can work without an external internet connection.  Is it possible to have an option added to enable this?  E.g via an environment variable or cmake option to get the files from a location on disk where they have been downloaded some other way.

**Comment by tlmquintino** [comment]
Hi. Thanks for reporting this.
In principle the tests should not fail (and not attempt to connect) if the data is already present in the local storage.
If you download all the listed files and place then in $BUILDDIR/tests then the test should automatically complete successfully without the network.
Please note that there are at least 2 tests that pull data: odc_get_test_data and odc_get_mars_client_test_data_mo

**Comment by tlmquintino** [comment]
Having had a look at the tests/ directory I realise we probably pull more data than needed for all the tests.
We will review the list to rationalise it to a shorter, leaner list.

**Comment by DJDavies2** [comment]
Thanks, I have put together the files that are needed and inserted them in tests and regressions and it seems to work now.  Thankis.
