### ISSUE TITLE
ctest failure in odc_legacy_fortran_api_examples

### ISSUE THREAD

**Issue by DJDavies2** [ecmwf/odc#9]
### What happened?

Running the ctest odc_legacy_fortran_api_examples test gives this output:

 Calling odb_start...
 example_fortran_api_setup
forrtl: severe (408): fort: (33): Shape mismatch: The extent of dimension 1 of array ONE_ROW is 4 and the corresponding extent of array <RHS expression> is 13

Image              PC                Routine            Line        Source             
libifcoremt.so.5   00002ACD2AEEA2C9  for_emit_diagnost     Unknown  Unknown
odc_legacy_fortra  00000000004086AE  example_fortran_a         200  legacy_fortran_api_examples.f90
odc_legacy_fortra  000000000040239F  MAIN__                     42  legacy_fortran_api_examples.f90
odc_legacy_fortra  00000000004022C2  Unknown               Unknown  Unknown
libc-2.17.so       00002ACD2E330555  __libc_start_main     Unknown  Unknown
odc_legacy_fortra  00000000004021D9  Unknown               Unknown  Unknown

### What are the steps to reproduce the bug?

This is with an Intel build with runtime checks on (e.g. bounds checking).

### Version

1.4.6

### Platform (OS and architecture)

RHEL7

### Organisation

Met Office

**Comment by simondsmart** [comment]
Should now be fixed, according to PR #10
